apiVersion: v1
name: naupakaio # This value was modified by the initial-setup python script
description: A Helm chart for deploying naupakaio-frontend. # This value was modified by the initial-setup python script
version: 1.0
