name: deploy-infra

trigger: none

pool:
  vmImage: 'ubuntu-latest' 
  # If you are using a self-hosted agent, comment out the previous line and uncomment the following three
  # name: <agent-pool-name> # Insert here the name of the agent pool you created
  # demands:
  #   - agent.name -equals <agent-name> # Insert here the name of the agent you created


steps:
- task: TerraformInstaller@0
  displayName: Install terraform
  inputs:
    terraformVersion: '1.4.6'

- task: TerraformCLI@0
  displayName: 'Terraform Init Backend'
  inputs:
    command: init
    workingDirectory: 'terraform/backend'
    providerServiceAws: 'aws' 
    providerAwsRegion: AATT_AWS_REGION # This value was modified by the initial-setup python script

- task: TerraformCLI@0
  displayName: 'Terraform Apply Backend'
  inputs:
    command: apply
    workingDirectory: 'terraform/backend'
    providerServiceAws: 'aws' 
    providerAwsRegion: AATT_AWS_REGION # This value was modified by the initial-setup python script
  continueOnError: true

- script: cp terraform/backend/terraform.tfstate terraform/aws
  displayName: 'Move terraform.tfstate to /terraform/aws/ directory'

- task: TerraformCLI@0
  displayName: 'Terraform Init Infra'
  inputs:
    command: init
    workingDirectory: 'terraform/aws'
    backendType: aws 
    backendServiceAws: aws 
    providerServiceAws: 'aws' 
    providerAwsRegion: AATT_AWS_REGION # This value was modified by the initial-setup python script
    commandOptions: '-force-copy'

- task: TerraformCLI@0
  displayName: 'Terraform Apply Infra'
  inputs:
    command: apply
    workingDirectory: 'terraform/aws'
    providerServiceAws: 'aws' 
    providerAwsRegion: AATT_AWS_REGION # This value was modified by the initial-setup python script
