name: application-build

trigger:
  branches:
    include:
      - main  # Include the branches where you want the trigger to apply
  paths:
    include:
      - my-app/*
# A ESTE HAY Q AGREGARLE UN WEBHOOK CON GITHUB PA Q BUILDEE CADA Q HAY UN CAMBIO EN EL CODIGO DE LA APP!!!!!!!!!!!!!!!!!!!!!!!!!!
# resources:
#   repositories:
#   - repository: automate-all-the-things # The name used to reference this repository in the checkout step
#     type: github
#     endpoint: tferrari92 # Name of the service connection # AATT_GITHUB_USERNAME # This value was modified by the initial-setup python script
#     name: tferrari92/automate-all-the-things # AATT_GITHUB_USERNAME
  # pipelines:
  # - pipeline: deploy-eks # any arbitrary name
  #   source: deploy-eks   # name of the pipeline shown on azure UI portal
  #   # source: "AATT_GITHUB_USERNAME.automate-all-the-things (2)"   # Name of the pipeline that needs to succeed for this pipeline to run # AATT_GITHUB_USERNAME
  #   trigger:
  #   branches:
  #     include:
  #       - main


pool:
  vmImage: 'ubuntu-latest' 
  # If you are using a self-hosted agent, comment out the previous line and uncomment the following three
  # name: <agent-pool-name> # Insert here the name of the agent pool you created
  # demands:
  #   - agent.name -equals <agent-name> # Insert here the name of the agent you created

jobs:
- job: BuildJob
  displayName: 'Build Job'
  steps:
  - task: DockerInstaller@0
    displayName: Install Docker
    inputs:
      dockerVersion: '17.09.0-ce'
    
  - task: Docker@2
    displayName: Build And Push Image
    inputs:
      containerRegistry: 'dockerhub'
      repository: 'tferrari92/cafe' # This value was modified by the initial-setup python script
      command: 'buildAndPush'
      Dockerfile: 'my-app/Dockerfile'


- job: DeployJob
  displayName: 'Deploy Job'
  dependsOn: BuildJob
  steps:

  # In this case it's necessary to specify the checkout with the persistCredential options set to true. This will enable us to push the changes to the repo
  - checkout: self
    persistCredentials: true

  - script: |
      sed 's/tag:.*/tag: $(Build.BuildId)/g' helm/my-app/values.yaml > helm/my-app/values.temp
      mv helm/my-app/values.temp helm/my-app/values.yaml
    displayName: Update Tag In values.yaml


  # - script: |
  #     new_tag=${{ $(Build.BuildId) }}
  #     echo $new_tag
  #     sed 's/tag:*/tag: $new_tag/g' helm/my-app/values.yaml
  #   displayName: Update Tag In values.yaml


  # - script: |
  #     echo $(Build.BuildId)
  #     cat helm/my-app/values.yaml
  #   displayName: Verify

  - script: |
      git config --global user.email "AzureDevOps@Build&DeployAppPipeline.com"
      git config --global user.name "Azure DevOps - Build & Deploy App Pipeline"
    displayName: 'Configure Git user'

  - script: |
      git checkout -b main
      git add helm/my-app/values.yaml 
      git commit -m "App version tag updated to $(Build.BuildId) by Azure DevOps"
      git push --set-upstream origin main
    displayName: 'Push changes to GitHub'
