name: destroy-all-the-things

trigger: none

variables:
  - group: aws-keys

pool:
  vmImage: 'ubuntu-latest' 
  # If you are using a self-hosted agent, comment out the previous line and uncomment the following three
  # name: <agent-pool-name> # Insert here the name of the agent pool you created
  # demands:
  #   - agent.name -equals <agent-name> # Insert here the name of the agent you created

jobs:
- job: DeleteK8SResources
  displayName: 'Delete Kubernetes Resources'
  steps:
  - task: KubectlInstaller@0
    inputs:
      kubectlVersion: '1.27.1'

  - task: AWSCLI@1
    displayName: 'Update KubeConfig'
    inputs:
      awsCredentials: 'aws'
      regionName: 'AATT_AWS_REGION' # This value was modified by the initial-setup python script
      awsCommand: 'eks'
      awsSubCommand: 'update-kubeconfig'
      awsArguments: '--name AATT_APP_NAME-cluster --region AATT_AWS_REGION' # This value was modified by the initial-setup python script

  - script: | # This value was modified by the initial-setup python script
      mkdir ~/.aws
      echo -e "[default]\naws_access_key_id = $(aws_access_key_id)\naws_secret_access_key = $(aws_secret_access_key)" > ~/.aws/credentials
      echo -e "[default]\nregion = AATT_AWS_REGION"> ~/.aws/config 
    displayName: 'Configure AWS Profile'

  - script: | # This value was modified by the initial-setup python script
        kubectl delete ingress -n AATT_APP_NAME $(kubectl get ingress -n AATT_APP_NAME | awk 'NR>1{print $1}')
        kubectl delete ingress -n argocd $(kubectl get ingress -n argocd | awk 'NR>1{print $1}')
    displayName: 'Delete Ingresses'
    # continueOnError: true


- job: DeleteAWSInfrastructure
  displayName: 'Delete AWS Infrastructure'
  dependsOn: DeleteK8SResources
  steps:
  - task: TerraformInstaller@0
    displayName: Install terraform
    inputs:
      terraformVersion: '1.4.6'

  - task: TerraformCLI@0
    displayName: 'Terraform Init'
    inputs:
      command: init
      workingDirectory: 'terraform/aws'
      backendType: aws
      backendServiceAws: aws
      providerServiceAws: 'aws'
      providerAwsRegion: AATT_AWS_REGION # This value was modified by the initial-setup python script

  - task: TerraformCLI@0
    displayName: 'Terraform Destroy AWS Infra'
    inputs:
      command: destroy
      workingDirectory: 'terraform/aws'
      providerServiceAws: 'aws'
      providerAwsRegion: AATT_AWS_REGION # This value was modified by the initial-setup python script
    continueOnError: true
