name: deploy-argocd

trigger: none

resources:
  repositories:
  - repository: automate-all-the-things # The name used to reference this repository in the checkout step
    type: github
    endpoint: tferrari92 # Name of the service connection
    name: tferrari92/automate-all-the-things
  pipelines:
  - pipeline: deploy-eks # any arbitrary name
    source: deploy-eks   # name of the pipeline shown on azure UI portal
    trigger:
    branches:
      include:
        - main

# trigger:
#   paths:
#     include:
#     - azure-devops/03-deploy-argocd.yml

pool:
  vmImage: 'ubuntu-latest'
  # Uncomment the three lines below and comment the previous line if you will use a self-hosted agent
  # name: lenovo # Agent Pool Name
  # demands:
  #   - agent.name -equals lenovo-agent # Agent Name

steps:
- task: HelmInstaller@0
  inputs:
    displayName: Install helm
    helmVersion: '2.14.1'
    installKubectl: true

- task: HelmDeploy@0
  displayName: Deploy argocd
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'k8s'
    command: 'install'
    chartType: 'FilePath'
    chartPath: 'helm/argocd'
    releaseName: 'argocd'

