resources:
  repositories:
  - repository: tomaco # The name used to reference this repository in the checkout step
    type: github
    endpoint: github.com_tferrari92 # Name of the service connection
    name: tferrari92/tomaco
#  - repository: MyBitbucketRepo
#    type: bitbucket
#    endpoint: MyBitbucketServiceConnection
#    name: MyBitbucketOrgOrUser/MyBitbucketRepo



trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  gitUsername: 'tferrari92'
  gitPassword: $(GitPassword) # Secret variable with Git credentials

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.4.6'


- checkout: tomaco



#- script: |
#    cd $(Build.Repository.LocalPath)/terraform/aws
#    terraform init
#    terraform plan
#    terraform apply --auto-approve