# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  gitUsername: 'tferrari92'
  gitPassword: $(GitPassword) # Secret variable with Git credentials

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.4.6'


- task: GitClone@2
  inputs:
    repository: 'https://$(gitUsername):$(gitPassword)@github.com/example/repo.git'
    clean: true



#- script: |
#    cd $(Build.Repository.LocalPath)/terraform/aws
#    terraform init
#    terraform plan
#    terraform apply --auto-approve