name: test

trigger: none

pool:
  vmImage: 'ubuntu-latest' 
  # If you are using a self-hosted agent, comment out the previous line and uncomment the following three
  # name: <agent-pool-name> # Insert here the name of the agent pool you created
  # demands:
  #   - agent.name -equals <agent-name> # Insert here the name of the agent you created


steps:


- script: echo 'this is Step 1'
  displayName: 'Step 1'
  continueOnError: true

- script: echo 'this is Step 1'
  displayName: 'Step 2'
  condition: succeeded()