apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cafe-argocd-application
  namespace: argocd
spec:
  destination:
    namespace: cafe
    server: https://kubernetes.default.svc
  project: default
  source:
    # helm:
    #   valueFiles:
    #     - ../values.yaml
    path: helm/my-app
    repoURL: https://github.com/tferrari92/automate-all-the-things.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true