apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.appName }}
  name: {{ .Values.appName }}-service
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
